e2eshark/README.md
=> Setup e2eshark test

e2eshark/README.md, e2eshark/run.py, e2eshark/tools/onnxutil.py, e2eshark/tools/stubrunmodel.py
added ability to count instances of ops in an onnx file, added ability to ready numpy input given to the framework model to drive the hardware run and compare gold generated from framework with the output received from hardware
=> run hardware inference using input given to framework model, compare result of framework with hw output

e2eshark/README.md, e2eshark/onnx/models/resnet50_vaiq_int8/model.py, e2eshark/requirements.txt, e2eshark/run.py, e2eshark/tools/stubonnxrunmodel.py
Would be needed to be able take large quantized files through the flow.
=> Add support for running zipped onnx file as input. 

e2eshark/README.md, e2eshark/onnx/models/resnet50/model.py, e2eshark/pytorch/models/llama2-7b-GPTQ/model.py, e2eshark/pytorch/models/opt-1.3b/model.py, e2eshark/pytorch/models/opt-125m-gptq/model.py, e2eshark/pytorch/models/resnet50/model.py, e2eshark/requirements.txt, e2eshark/run.py, e2eshark/tools/stubs/pytorchmodel.py
=> add int8 models for opt-125M, add resenet pytorch fp32 models, 

e2eshark/README.md, e2eshark/onnx/combinations/constant_constantofshape/model.py, e2eshark/onnx/combinations/mlp/model.py, e2eshark/onnx/models/resnet50_vaiq_int8/model.py, e2eshark/onnx/operators/add/model.py, e2eshark/run.py, e2eshark/tools/stubs/onnxmodel.py, e2eshark/tools/stubs/pytorchmodel.py
gemm and mlp are breaking the linalg lowering
=> support for multiple inputs for onnx tests, added gemm, mlp, add tests

e2eshark/run.py, e2eshark/tools/stubs/commonutils.py
https://github.com/nod-ai/SHARK-TestSuite/issues/46 fixed, uses now current phase name
The tools.stubs.commonutils is included in run.py and model.py to allow building any arbitrary post processing pipeline to allow meaningful comparison of outputs for quantized models
=> Fix issue #46 and make post process pipeline use common code

e2eshark/tools/stubs/turbinemodel.py
minor change to account turbine updates
=> update variable name

e2eshark/onnx/operators/MatMul/model.py, e2eshark/onnx/operators/Mul/model.py, e2eshark/onnx/operators/Softmax/model.py
This PR adds couple of e2e onnx testcases, specifically 
MatMul
Mul
Softmax
=> Adding MatMul, elementwise Mul and Softmax

e2eshark/onnx/operators/equal/model.py, e2eshark/run.py
failed: `In unpackBytearray, found an unsupported data type torch.bool`
=> Add onnx equal op test

e2eshark/onnx/operators/flatten/model.py
=> Add onnx flatten op test

e2eshark/onnx/operators/gelu/model.py
=> [onnx] Gelu e2e testcase

e2eshark/onnx/operators/layernorm/model.py
E2E test for Layernorm 
Therefore we have all e2e testcases required for attention head.
=> layernorm e2e testcase

e2eshark/onnx/operators/gemm2/model.py
Testcases which test Gemm with and without Bias. 
This means 2 inputs are also allowed, which is pretty much a classic matmul implementation.
=> Gemm support with and without bias

e2eshark/gold/upload_list.txt, e2eshark/requirements.txt, e2eshark/run.py
add requirement of simplejson and pull datetime out so it is same in storage for test artifacts (needed due to multiprocessing).
=> add requirements + cleanup

e2eshark/run.py
Add ERROR prefix for error messages
=> take atol and rtol as pair like torch.testing requires and have good known defaults

e2eshark/pytorch/models/gemma-7b/model.py
Add initial structure for gemma through e2eshark
=> add gemma-7b structure

iree_tests/conftest.py
This will help with https://github.com/openxla/iree/pull/16801#discussion_r1526966272
=> Skip IREE test cases if git LFS files are not present.

e2eshark/pytorch/operators/silu/model.py
I added a testcase for SiLU as of Elliott's request.
=> Added testcase for SiLU

e2eshark/onnx/models/CSP-DarkNet_vaiq_int8/model.py, e2eshark/onnx/models/KeypointRCNN_vaiq_int8/model.py, e2eshark/onnx/models/RAFT_vaiq_int8/model.py, e2eshark/onnx/models/U-2-Net_vaiq_int8/model.py, e2eshark/onnx/models/pytorch-3dunet_vaiq_int8/model.py, e2eshark/tools/aztestsetup.py
- fixes creation of ghost zip file when download fails 
- adds support for remaining onnx models to testsuite
=> Add onnx models 2 and ghsot zip fix

e2eshark/pytorch/operators/gridsampler2/model.py
gridsampler has a parameter to select how corners and edges are aligned. 
The two options are now implemented and therefore two cases are provided with this PR.
=> Added a second gridsampler testcase to test both align_corners modes

e2eshark/README.md, e2eshark/pytorch/operators/silu/model.py
1. Added prerequisite 
2. missing directory in shark test example
3. added note as version of torch-mlir-wheel keep changing
=> Updating Readme

e2eshark/onnx/operators/BlackmanWindow/model.py
Adds an e2e test for `onnx.BlackmanWindow`.
=> Add test for onnx.BlackmanWindow

iree_tests/update_config_xfails.py
Progress on https://github.com/nod-ai/SHARK-TestSuite/issues/202 (still requires manual parsing through logs, can automate that separately)
=> Add script to help update XFAIL sets in config.json files.

e2eshark/onnx/models/opt-125M-awq/model.py, e2eshark/run.py, e2eshark/tools/stubs/onnxmodel.py
I'm not sure how I feel about saving the dynamic model to the test bin. Any suggestions?
This also fixes an issue with a random int64 input always being zero.
=> Adds option to run opt-125M-awq as a static model

e2eshark/onnx/operators/resize_linear/model.py, e2eshark/onnx/operators/resize_nearest/model.py
python run.py -c ../../../torch-mlir/build -i ../../../iree-build/ -f onnx  --tests onnx/operators/resize_linear --cachedir cachedir --report
=> resize e2e test

e2eshark/onnx/operators/HammingWindow/model.py
Adds e2e test for the `onnx.HammingWindow` op.
=> Add test for onnx.HammingWindow

e2eshark/README.md
No functional changes in here - just adding backticks for code, turning references to files into hyperlinks, adjusting spacing, setting code block languages, etc.
=> Proofreading and formatting pass through e2eshark/README.md.

e2eshark/onnx/operators/SequenceConstruct/model.py
This test is still failing in irre, as it requires a sequence as return to a function, which iree
does not seem to support at the moment.
=> Added an onnx.SequenceConstruct test.

e2eshark/onnx/combinations/SequenceLength/model.py
This also ends up testing onnx.SequenceConstruct and is a combined test so that we can make sure it works without passing a sequence across a function boundary.
=> Added an onnx.SequenceLength test.

e2eshark/run.py
adds support so we can also call the source build iree-import-onnx
=> iree-import-onnx source build support

.github/workflows/test_iree.yml
Small cleanup / deduplication here in this repo, mostly testing the workflow style to follow it in the IREE repo where we test across more configurations.
=> Rework test_iree.yml to use a matrix strategy.

e2eshark/onnx/operators/Loop/model.py
- add simple onnx.Loop testcase
=> add onnx Loop

.github/workflows/test_e2eshark.yml, e2eshark/onnx/models/RDN_pytorch_vaiq_int8/model.py, e2eshark/onnx/models/RRDB_ESRGAN_vaiq_int8/model.py, e2eshark/onnx/models/pytorch-3dunet_vaiq_int8/model.py, e2eshark/pytorch/models/gpt2-xl/model.py, e2eshark/pytorch/models/gpt2/model.py, e2eshark/pytorch/models/mit-b0/model.py, e2eshark/pytorch/models/t5-base/model.py, e2eshark/pytorch/models/t5-large/model.py
This commit updates the post processing/tolerance for the mismatching models.
=> Update postprocess/tolerance for e2e model testing.

e2eshark/onnx/operators/LpPool/model.py
https://github.com/llvm/torch-mlir/pull/3449
cc: @vivekkhandelwal1  @zjgarvey
=> add lppool e2e test

e2eshark/onnx/operators/GlobalLpPool/model.py
https://github.com/llvm/torch-mlir/pull/3435
CC: @zjgarvey  @vivekkhandelwal1
=> Add e2e test for global lp pool

iree_tests/sharktank/punet/fp16/test_cases.json, iree_tests/sharktank/punet/int8/test_cases.json
This mainly pulls in
* https://github.com/nod-ai/sharktank/commit/0b67e6aca5185fc517814bd631f821798e1ee26b (fix to enable a compiler optimization)
* https://github.com/nod-ai/sharktank/commit/b5aef1037207bc9abc67c0f70fcbffcb53e681a7 (adapting to quantized parameter changes)
=> Bump punet .mlir and .irpa files to latest from HF.

e2eshark/onnx/models/efficientnet_b1.ft_in1k_vaiq/model.py, e2eshark/onnx/models/efficientnet_b2.ra_in1k_vaiq/model.py, e2eshark/onnx/models/efficientnet_b3.ra2_in1k_vaiq/model.py, e2eshark/onnx/models/efficientnet_b4.ra2_in1k_vaiq/model.py, e2eshark/onnx/models/efficientnetv2_rw_m.agc_in1k_vaiq/model.py, e2eshark/onnx/models/efficientnetv2_rw_s.ra2_in1k_vaiq/model.py, e2eshark/onnx/models/resnet32ts.ra2_in1k_vaiq/model.py, e2eshark/onnx/models/resnet33ts.ra2_in1k_vaiq/model.py
model run log show the input size setting is wrong, change them to the new one.
=> Fix several input size for p0p1 int8 models

iree_tests/configs/onnx_cpu_llvm_sync.json, iree_tests/onnx/import_tests.py, iree_tests/onnx/import_tests_utils.py
Test generator does not handle all type imports. Fixed the test generator so that we actually convert the types correctly.
=> [onnx] Fix test generator for better type information

alt_e2eshark/reports/test_add.json, alt_e2eshark/reports/test_add.md, alt_e2eshark/reports/test_conv.json, alt_e2eshark/reports/test_conv.md, alt_e2eshark/reports/test_conv_and_add.json, alt_e2eshark/reports/test_conv_and_add.md, alt_e2eshark/run.py, alt_e2eshark/utils/merge_dicts.py, alt_e2eshark/utils/report.py
One of the items for <https://github.com/nod-ai/SHARK-TestSuite/issues/300>
=> [alt] add a report merging tool

alt_e2eshark/e2e_testing/test_configs/onnxconfig.py
pip install of torch-mlir doesn't include torch-mlir-opt, so `-m cl-onnx-iree --torchtolinalg` doesn't work with pip installs.
=> [alt] preprocess: fallback to iree-opt if torch-mlir-opt not found

alt_e2eshark/e2e_testing/storage.py
Following up on some work by @AmosLewis, I noticed another bug with i32 inputs.
=> Fix some quirks in get shape string, fix saving an int32 input

alt_e2eshark/onnx_tests/models/azure_models.py
Fix the onnx.if different shapes issue https://github.com/nod-ai/SHARK-ModelDev/issues/696 in model list https://github.com/pdhirajkumarprasad/SHARK-TestSuite/blob/feature/qa/issue/onnx-to-torch/onnx.if
4 dynamic models still left unfixed.
=> Fix the coat model with onnx.if different shapes bug

.github/workflows/test_e2eshark.yml
remove alt e2eshark branch checkout
=> Minor CI Fix

alt_e2eshark/onnx_tests/models/azure_models.py
Details available at https://github.com/nod-ai/SHARK-ModelDev/issues/883
=> added list of model in basic_opt otherwise was failing during compilation

alt_e2eshark/onnx_tests/models/nlp.py
model--bsc-bio-ehr-es-pharmaconer--PlanTL-GOB-ES pass the test with this fix.
The attention_mask input has to limit to 0/1
=> Fix nlp model input attention_mask issue

alt_e2eshark/e2e_testing/onnx_utils.py, alt_e2eshark/e2e_testing/storage.py
Noticed some lacking input generation support for `float16` and a bug for these cases in `storage.py`.
=> Add some f16 input support

alt_e2eshark/onnx_tests/operators/layer_norm.py, alt_e2eshark/onnx_tests/operators/model.py
`python run.py --mode=cl-onnx-iree -v --torchtolinalg -t layer_norm_test`
=> Add layer_norm e2e test with stash_type

alt_e2eshark/onnx_tests/models/onnx_zoo_models.py
Implements all custom registry classes for models from the ONNX Model Zoo.
=> Implement custom registry classes for ONNX Zoo Models

alt_e2eshark/onnx_tests/models/onnx_zoo_models.py
After adding them in opt list, it's passing numerics
=> Added model to basic opt list to make it work

alt_e2eshark/onnx_tests/models/onnx_zoo_models.py
=> Added model in basic opt

alt_e2eshark/base_requirements.txt, alt_e2eshark/onnx_tests/helper_classes.py, alt_e2eshark/onnx_tests/models/hf_models.py
Fixes a number of setup failures in HF Model support.
The `HfDownloadableModel` now respects the cache directory. and multiple choice models have better input generation.
Also fixes input mismatch between tokenization and the ONNX models in Deberta and Roberta models.
=> Fix setup failures for HF Models

.github/workflows/test_onnx_zoo.yml
=> Adding CI for onnx zoo model

alt_e2eshark/onnx_tests/helper_classes.py, alt_e2eshark/onnx_tests/models/hf_models.py
Cleans up test classes for HF Models, and adds a `basic_opt` registry for models requiring O1 optimization.
=> Cleanup HF models test implementation

.github/workflows/test_hf_top_1000_models.yml
=> test_hf_top_1000_models.yml

alt_e2eshark/onnx_tests/models/hf_models.py
Updates tokenizer input registry for failing HuggingFace models with extra tokenizer attributes.
=> Update tokenizer input registry for HF models

alt_e2eshark/onnx_tests/helper_classes.py, alt_e2eshark/onnx_tests/models/external_lists/hf-model-paths/hf-audio-classification-model-list.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-paths/hf-feature-extraction-model-list.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-shards/hf-audio-classification-shard.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-shards/hf-feature-extraction-shard.txt, alt_e2eshark/onnx_tests/models/hf_models.py
Adds extra input during construct_input phase to avoid input vs session_input size mismatch issue during native inference.
=> Fixes native inference input size mistmatch issue

alt_e2eshark/onnx_tests/models/external_lists/hf-model-paths/hf-fill-mask-model-list.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-paths/hf-multiple-choice-model-list.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-paths/hf-sentence-similarity-model-list.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-shards/hf-fill-mask-shard.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-shards/hf-multiple-choice-shard.txt, alt_e2eshark/onnx_tests/models/external_lists/hf-model-shards/hf-sentence-similarity-shard.txt, alt_e2eshark/onnx_tests/models/hf_models.py
Fixes following setup issues:
https://github.com/nod-ai/SHARK-ModelDev/issues/919
https://github.com/nod-ai/SHARK-ModelDev/issues/921
=> Setup issues fixes

.github/workflows/test_e2eshark.yml, .github/workflows/test_e2eshark_for_weekly.yml, alt_e2eshark/onnx_tests/models/external_lists/vai-hf-cnn-fp32-shard2_unique.txt
Fix the CI name and removed one mode which is causing failure. will debug that separately
=> Fix the CI name and removed one mode which is causing failure. 
