nod-ai/SHARK-TestSuite

- e2eshark/pytorch/combinations/mlp/model.py
- e2eshark/pytorch/models/dlrm/model.py
- e2eshark/pytorch/models/llama2-7b-hf/model.py
- e2eshark/pytorch/models/opt-125M/model.py
- e2eshark/pytorch/operators/conv2d/model.py
- e2eshark/pytorch/operators/linear/model.py
- e2eshark/tools/stubs/pytorchmodel.py
For some cases, torch_mlir.compile still works better, add ability to override fx importer usage in test case to get maximum number of designs to work
> add ability to use Fx importer for pytorch to torch MLIR 

- e2eshark/README.md
- e2eshark/onnx/combinations/constant_constantofshape/model.py
- e2eshark/onnx/models/resnet50/model.py
- e2eshark/onnx/models/resnet50_vaiq_int8/model.py
- e2eshark/run.py
- e2eshark/tools/stubs/onnxmodel.py
- e2eshark/tools/stubs/pytorchmodel.py
uniform way of saving input and gold output using torch.save and applying input to iree-run-module using raw binary to allow bfloat16 handling down the road
> uniform way of saving input and gold output 

- e2eshark/pytorch/combinations/mlp/model.py
- e2eshark/pytorch/models/dlrm/model.py
- e2eshark/pytorch/models/llama2-7b-GPTQ/model.py
- e2eshark/pytorch/models/llama2-7b-hf/model.py
- e2eshark/pytorch/models/opt-1.3b/model.py
- e2eshark/pytorch/models/opt-125M/model.py
- e2eshark/pytorch/models/opt-125m-gptq/model.py
- e2eshark/pytorch/models/resnet50/model.py
- e2eshark/pytorch/operators/conv2d/model.py
- e2eshark/pytorch/operators/linear/model.py
- e2eshark/run.py
- e2eshark/tools/stubs/pytorchmodel.py
- e2eshark/tools/stubs/utils.py
- This PR fixes execution upto OPT-125M Bf16 test running and giving mismatched result
- fix expected output of pytorch model to be a List[Tensor] which earlier was nested tuples 
- fix number of vmfb output mismatch in run-inference
- fix uses test_modelname to skip model input type conversion when importing models of different dtypes also add change for corresponding models
> Opt bf16 debug

- e2eshark/gold/upload_list.txt
- e2eshark/requirements.txt
- e2eshark/run.py
This commit allows the user to specify cleanup and upload command line options. The cleanup option allows the user to run the tests with space efficiency (removing mlir and vmfb files by default). Which types of files are removed can be changed by the user. Also, there is an uploading feature introduced. This allows the user to specify a list of tests in the `gold/upload_list.txt` file. If the test that the user is running falls in this list, the file types that the user choses are uploaded to an Azure space. They are organized here with unique identifier based on test name + date + UTC time so we won't try uploading to the same name. Also, after running the suite, a `upload_urls.txt` file is created. In this file, you can find a mapping of the test name to Azure link. This way the user …
> add cleanup + uploading features

- e2eshark/run.py
Parameters added to provide tolerances for comparing the test results.
--atol
--rtol 
For example: 
python ./run.py -c /home/ubuntu/E2E_MLIR_IREE/TORCH_MLIR/torch-mlir_main_af/build -i /home/ubuntu/E2E_MLIR_IREE/IREE/iree-build --report --cachedir /home/ubuntu/E2E_MLIR_IREE/CacheDir --tests pytorch/models/opt-1.3b --atol 1e-03 --rtol 1e-03
> Adding tolerance parameters --atol and --rtol to run.py script

- iree_tests/conftest.py
If a test unexpectedly passes the compilation phase, this now keeps going and tests the runtime. Depending on the outcome, a specific message is logged allowing for easier updating of config files. Updating is still a manual process, but it now requires less moving test cases back and forth between XFAIL lists.
Sample logs:
```
________ IREE compile and run: test_averagepool_2d_precomputed_strides::cpu_llvm_sync_test ________ [gw20] win32 -- Python 3.11.2 D:\dev\projects\SHARK-TestSuite\iree_tests\nightly_pip.venv\Scripts\python.exe
[XPASS(strict)] Expected compile to fail (remove from 'expected_compile_failures')
```
```
___ IREE compile and run: test_dynamicquantizelinear_min_adjusted_expanded::cpu_llvm_sync_test ____ [gw50] win32 -- Python 3.11.2 …
```
> Rework iree_tests to keep going after compile XPASS.

- e2eshark/onnx/models/RAFT_vaiq_int8/model.py
- e2eshark/onnx/models/RDN_pytorch_vaiq_int8/model.py
- e2eshark/onnx/models/pytorch-3dunet_vaiq_int8/model.py
RAFT_vaiq_int8
RDN_pytorch_vaiq_int8
pytorch-3dunet_vaiq_int8
(no change in MobileNetV3_small_vaiq_int8 needed)
Generated issues #598 #599
This commit is to provide correctly adapted model.py files to allow the test cases to run. 
model.onnx need to be downloaded still.
> Model Tests with working model.py

- e2eshark/onnx/operators/ReduceProdKeepdims0/model.py
- e2eshark/onnx/operators/ReduceProdKeepdims1/model.py
Pass all tests with https://github.com/llvm/torch-mlir/pull/3134
```
| tests                              | model-run   | onnx-import   | torch-mlir   | iree-compile   | inference   |
|:-----------------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| onnx/operators/ReduceProdKeepdims1 | passed      | passed        | passed       | passed         | passed      |
|:-----------------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| onnx/operators/ReduceProdKeepdims0 | passed      | passed        | passed       | passed         | passed      |
```
> Add e2e tests for ReduceProd with keeepdims attributes

- e2eshark/onnx/combinations/QuantizeToMatMulInteger/model.py
- e2eshark/run.py
This is to test some work I'm doing on quantized batch matmul in torch-mlir to get Opt-125m to lower to linalg. 
For now, I'm focusing on the one case I'm seeing in opt-125m which is rank3 x rank2 -> rank3 MatMulInteger ops.
> Adds an e2e test for DQL -> MatMulInteger seen in Opt

- .github/workflows/test_iree.yml
- iree_tests/download_remote_files.py
This commit adds caching support for model testing. This brings the download time from ~20 mins to 23 seconds. With these changes, it is feasible to add model testing as a presubmit in the iree repo which was the reason for these changes. 
Description of what's going on:  
First, we use an environment variable passed in (IREE_TEST_FILES) to determine if we even want to use a cache or not (don't want to make it a requirement). In CI, we set this because we want a persistent runner cache. If this is set, we download files to the cache location specified and symlink it to the testing directory. Otherwise, we just directly download into the repo, and it won't be using any caching mechanism. The test runner doesn't need to know about caching at all, and even initially, it will just create the …
> Add caching support for model testing

- e2eshark/onnx/operators/If/model.py
- e2eshark/run.py
Simple op test for if. Also includes a nifty little helper function that would reduce error & duplication by avoiding re-specifying dtypes and shapes
```python
inputs = session.get_inputs()
outputs = session.get_outputs()
def generate_input_from_node(node: onnxruntime.capi.onnxruntime_pybind11_state.NodeArg):
if node.type == "tensor(float)":
return numpy.random.randn(*node.shape).astype(numpy.float32)
if node.type == "tensor(int)":
return numpy.random.randint(0, 10000, size=node.shape).astype(numpy.int32)
if node.type == "tensor(bool)":
return numpy.random.randint(0, 2, size=node.shape).astype(bool)
input_dict = {
node.name: generate_input_from_node(node)
for node in inputs
}
output_list = [
node.name
for node in outputs
]
```
> Onnx.if op test

- .github/workflows/test_iree.yml
- iree_tests/README.md
- iree_tests/conftest.py
I wanted developers to be able to run the full test suite without needing to download all files. That meant skipping tests if files were not downloaded. On CI machines, we probably want to fail instead of skipping tests, as we _should_ be downloading all files or pulling them from a cache. This adds a flag that lets us control that behavior.
> Add option to fail pytest collection if files are missing.

- iree_tests/download_remote_files.py
A few improvements for local workflows:
* Allow passing the cache directory via either an environment variable or a CLI flag
* Delete preexisting files before writing out a symlink to fix `FileExistsError: [WinError 183] Cannot create a file when that file already exists` on Windows
* Pull code into a helper function so it can be shared between Azure file downloading and generic (GCS/Huggingface/etc.) file downloading
* Update a few variable names and docstrings
> Refactor how download_remote_files handles cache directories.

- .github/workflows/test_e2eshark.yml
- e2eshark/ci-requirements.txt
- e2eshark/requirements.txt
will pin numpy if everyone experiences the pip installing the pre release version
> Update requirements and get CI working for e2eshark

- .github/workflows/test_iree.yml
- iree_tests/conftest.py
Fixes https://github.com/nod-ai/SHARK-TestSuite/issues/223
More can be added later. For now, this makes setting `--log-cli-level=info` include some extra info for each test case regardless of whether the test passed or failed:
```
iree_tests/pytorch/models/sdxl-vae-decode-tank/model.mlirbc::gpu_rocm_real_weights 
-------------------------------- live log call ---------------------------------
INFO     root:conftest.py:393 Launching compile command:
cd /mnt/share/amdsharks/actions-runner/_work/SHARK-TestSuite/SHARK-TestSuite/iree_tests/pytorch/models/sdxl-vae-decode-tank && iree-compile model.mlirbc --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx90a --iree-opt-const-eval=false --iree-codegen-transform-dialect-library=/mnt/share/amdsharks/actions-runner/_work/SHARK-TestSuite/SHAR …
```
> Support logging compile and run commands even if successful.

- e2eshark/run.py
There tests all based on the torch-mlir&iree llvm b3291793f119 Apr 30 and iree a075013cf May 7th.
`python ./run.py --torchmlirbuild ../../torch-mlir/build --tolerance 0.001 0.001 --cachedir ./huggingface_cache --ireebuild ../../iree-build  -f pytorch -g models --mode onnx --report`
Status report for run: test-run using mode:onnx todtype:default backend:llvm-cpu
| tests                                            | model-run   | onnx-import   | torch-mlir   | iree-compile   | inference   |
|:-------------------------------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| pytorch/models/gpt2                              | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/opt-125M …
> Fix the torchtolinalg == False passpipeline

- iree_tests/README.md
- iree_tests/pytorch/models/import_from_e2eshark.py
This keeps the documentation up to date with instructions that worked on my Windows machine.
Unfortunately I wasn't able to regenerate test cases for resnet50 or opt-125M:
* resnet50 crashed in the compiler at `mlir::iree_compiler::IREE::Util::serializeResourceRawData D:\dev\projects\iree\compiler\src\iree\compiler\Dialect\Util\IR\UtilAttrs.cpp:230:0`
* opt-125M regressed in PyTorch at some point - I can't even export it to torch-mlir (marked as failing, along with nearly all other models, at https://github.com/nod-ai/e2eshark-reports/blob/main/2024-05-07/turbine_reports/statusreport.md)
> Refresh docs and flags for importing from e2eshark to IREE.

- e2eshark/pytorch/models/bart-large/model.py
- e2eshark/pytorch/models/beit-base-patch16-224-pt22k-ft22k/model.py
- e2eshark/pytorch/models/bert-large-uncased/model.py
- e2eshark/pytorch/models/bge-base-en-v1.5/model.py
- e2eshark/pytorch/models/deit-small-distilled-patch16-224/model.py
- e2eshark/pytorch/models/gpt2-xl/model.py
- e2eshark/pytorch/models/gpt2/model.py
- e2eshark/pytorch/models/miniLM-L12-H384-uncased/model.py
- e2eshark/pytorch/models/mit-b0/model.py
- e2eshark/pytorch/models/mobilebert-uncased/model.py
- e2eshark/pytorch/models/opt-1.3b/model.py
- e2eshark/pytorch/models/opt-125M/model.py
- e2eshark/pytorch/models/opt-125m-gptq/model.py
- e2eshark/pytorch/models/opt-350m/model.py
- e2eshark/pytorch/models/phi-1_5/model.py
- e2eshark/pytorch/models/phi-2/model.py
- e2eshark/pytorch/models/resnet50/model.py
- e2eshark/pytorch/models/stablelm-3b-4e1t/model.py
- e2eshark/pytorch/models/t5-base/model.py
- e2eshark/pytorch/models/t5-large/model.py
- e2eshark/pytorch/models/vicuna-13b-v1.3/model.py
- e2eshark/pytorch/models/vit-base-patch16-224/model.py
- e2eshark/pytorch/models/whisper-base/model.py
- e2eshark/pytorch/models/whisper-medium/model.py
- e2eshark/pytorch/models/whisper-small/model.py
- e2eshark/pytorch/operators/conv2d/model.py
- e2eshark/pytorch/operators/gridsampler/model.py
- e2eshark/pytorch/operators/gridsampler2/model.py
- e2eshark/pytorch/operators/silu/model.py
Progress on https://github.com/nod-ai/SHARK-TestSuite/issues/49
According to my IDE and some local running, these imports were unused. The `import torch_mlir` lines are particularly problematic, as torch-mlir on its own is not distributed for downstream projects to use (there are nightly Linux packages for some developer use, but downstream projects like IREE take a source dependency on torch-mlir and ship their own packages).
> Remove unused imports from e2eshark/pytorch/**/model.py files.

- .github/workflows/test_iree.yml
- iree_tests/configs/config_pytorch_models_cpu_llvm_task.json
- iree_tests/configs/config_sdxl_prompt_encoder_cpu_llvm_task.json
- iree_tests/configs/config_sdxl_prompt_encoder_gpu_rocm.json
- iree_tests/configs/config_sdxl_scheduled_unet_gpu_rocm.json
- iree_tests/configs/config_sdxl_vae_decode_cpu_llvm_task.json
- iree_tests/configs/config_sdxl_vae_decode_gpu_rocm.json
- iree_tests/pytorch/models/sdxl-prompt-encoder-tank/real_weights_data_flags.txt
- iree_tests/pytorch/models/sdxl-vae-decode-tank/real_weights_data_flags.txt
This commit adds support so that we can have different configuration files based on the backend for every sdxl model. This now gives us model and backend independence for all flags in sdxl
> Add support for backend specific config files for sdxl models.

- e2eshark/tools/stubs/turbinemodel.py
See https://github.com/nod-ai/SHARK-TestSuite/pull/231#discussion_r1621444654. This fixes
```
Traceback (most recent call last):
File "D:\dev\projects\SHARK-TestSuite\e2eshark\test-run\pytorch\models\opt-125M\runmodel.py", line 145, in <module>
torch.save(E2ESHARK_CHECK["input"], inputsavefilename)
^^^^^
NameError: name 'torch' is not defined
```
Individual model files had this import but did not use it directly. Imports should be added where they are used.
> Add missing `import torch` to turbinemodel stub.

- e2eshark/requirements.txt
- iree_tests/README.md
Follow-up to https://github.com/nod-ai/SHARK-TestSuite/pull/231 and https://github.com/nod-ai/SHARK-TestSuite/pull/232.
Some parts of e2eshark won't work without standalone torch-mlir packages, but this helps users on macOS and Windows follow the setup instructions as-is to run the parts that do work (e.g. turbine).
> Skip installing torch-mlir automatically on non-Linux.

- e2eshark/pytorch/models/bart-large/model.py
- e2eshark/pytorch/models/bert-large-uncased/model.py
- e2eshark/pytorch/models/bge-base-en-v1.5/model.py
- e2eshark/pytorch/models/gemma-7b/model.py
- e2eshark/pytorch/models/gpt2-xl/model.py
- e2eshark/pytorch/models/gpt2/model.py
- e2eshark/pytorch/models/llama2-7b-GPTQ/model.py
- e2eshark/pytorch/models/llama2-7b-hf/model.py
- e2eshark/pytorch/models/miniLM-L12-H384-uncased/model.py
- e2eshark/pytorch/models/opt-1.3b/model.py
- e2eshark/pytorch/models/opt-125M/model.py
- e2eshark/pytorch/models/opt-125m-gptq/model.py
- e2eshark/pytorch/models/opt-350m/model.py
- e2eshark/pytorch/models/phi-1_5/model.py
- e2eshark/pytorch/models/phi-2/model.py
- e2eshark/pytorch/models/stablelm-3b-4e1t/model.py
- e2eshark/pytorch/models/vicuna-13b-v1.3/model.py
- e2eshark/pytorch/models/whisper-base/model.py
- e2eshark/pytorch/models/whisper-medium/model.py
- e2eshark/pytorch/models/whisper-small/model.py
Fixes https://github.com/nod-ai/SHARK-TestSuite/issues/105
These tokenizers sometimes output characters that cause trouble when printing with the default encoding on Windows, so explicitly encode as utf8. Not all tests currently generate such characters, but the extra safety seems helpful.
Sample response from whisper-small: `Response: b'<|startoftranscript|><|notimestamps|>What is nature of our existence?<|endoftext|>\xef\xbf\xbd\xef\xbf\xbd<|zh|>\xd0\xb7\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xe5\x84\x89\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd<|endoftext|>'`
* `UnicodeEncodeError: 'charmap' codec can't encode characters in position 82-83: character maps to <undefined>` (those are the `\xef\xbf` characters, unicode …
> Encode tokenizer outputs as utf8 before printing them.

- .github/workflows/test_e2eshark.yml
- e2eshark/README.md
- e2eshark/requirements.txt
This commit updates the workflow and readme to use both the repos and latest dependencies, so we are no longer pinned to torch 2.1.
> Update turbine mode to use latest SHARK setup.

- e2eshark/onnx/operators/AveragePool/model.py
count_include_pad PR: https://github.com/llvm/torch-mlir/pull/3235
count_include_pad issue: https://github.com/nod-ai/SHARK-Turbine/issues/643
dilations issue: https://github.com/llvm/torch-mlir/issues/3428
dilations pr: https://github.com/llvm/torch-mlir/pull/3490
Status report for run: test-run using mode:onnx todtype:default backend:llvm-cpu
| tests                      | model-run   | onnx-import   | torch-mlir   | iree-compile   | inference   |
|:---------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| onnx/operators/AveragePool | passed      | passed        | passed       | passed         | passed      |
> Add e2e test for AveragePool with count_include_pad/dilations attribute

- e2eshark/onnx/models/DeepLabV3_resnet50_vaiq_int8/model.py
- e2eshark/onnx/models/FCN_vaiq_int8/model.py
- e2eshark/onnx/models/RAFT_vaiq_int8/model.py
- e2eshark/onnx/models/U-2-Net_vaiq_int8/model.py
- e2eshark/onnx/models/YoloNetV3_vaiq_int8/model.py
- e2eshark/onnx/models/u-net_brain_mri_vaiq_int8/model.py
- e2eshark/onnx/models/yolov8n_vaiq_int8/model.py
https://github.com/nod-ai/SHARK-Turbine/issues/683
When using iree with local changes that fixed `iree-compile` compilation errors, the test started to fail in inference (`iree-run-module`). I was specifically running the RAFT test. This seemed to be due to accessing `E2ESHARK_CHECK` with "inputs" instead of "input".
After fixing that I got a different inference error due to a mismatch between expected outputs and the outputs of the vmfb. I grepped  `OUT_OF_RANGE` and found other tests failing in the same way (found in model's `inference.log` file). There could be other tests that are failing earlier than inference that have this same issue.
> onnx `model.py` fix

- .github/workflows/test_iree.yml
Might as well have this running on a schedule so we can compare results on PRs to a baseline.
I chose 8AM PST since IREE nightly releases typically finish building around 6:45AM PST (see times on https://github.com/iree-org/iree/actions/workflows/validate_and_publish_release.yml)
> Run IREE Test Suite on a nightly schedule.

- iree_tests/download_remote_files.py
- iree_tests/sharktank/punet/.gitignore
- iree_tests/sharktank/punet/fp16/real_weights_data_flags.txt
- iree_tests/sharktank/punet/fp16/sdxl_fp16_export_mlir.mlirbc
- iree_tests/sharktank/punet/fp16/test_cases.json
- iree_tests/sharktank/punet/int8/real_weights_data_flags.txt
- iree_tests/sharktank/punet/int8/sdxl_int8_export_mlir.mlirbc
- iree_tests/sharktank/punet/int8/test_cases.json
See https://huggingface.co/amd-shark/sdxl-quant-models, which is now a source of truth for developers interfacing with this model. For now the files are pinned to a commit hash as changes are expected over the coming days.
Some details:
* I needed to update the regex in `download_remote_files.py` to support subdirectories. The `/` search was greedy, capturing e.g. `fe57fe12eeb6eac83f469793984f6ad4c06a478c/unet/fp16/export` and `sdxl_unet_fp16_dataset.irpa` instead of `fe57fe12eeb6eac83f469793984f6ad4c06a478c` and `unet/fp16/export/sdxl_unet_fp16_dataset.irpa`.
* This benefits from https://github.com/nod-ai/SHARK-TestSuite/pull/282, since the `.mlir` file that the test collector looks for is a remote file not downloaded with a regular Git [LFS] checkout. That PR changes the collector to …
> Switch punet tests to use .mlir and .irpa files from Hugging Face.

- iree_tests/conftest.py
This allows us to detect test cases that store their `.mlir` or `.mlirbc` file remotely, since the `test_data_flags.txt` or `test_cases.json` file will always exist locally. This also changes test case names in summaries from e.g. 
```
PASSED onnx/node/generated/test_sub_uint8/model.mlir::cpu_llvm_sync_test
PASSED onnx/node/generated/test_sub_example/model.mlir::cpu_llvm_sync_test
PASSED onnx/node/generated/test_sub_bcast/model.mlir::cpu_llvm_sync_test
XFAIL pytorch/models/opt-125M/opt-125M.mlirbc::cpu_llvm_task_splats - Expected compilation to fail (included in 'expected_compile_failures')
```
to e.g.
```
PASSED onnx/node/generated/test_sub_example/test_data_flags.txt::model.mlir::cpu_llvm_sync
PASSED onnx/node/generated/test_sub_uint8/test_data_flags.txt::model.mlir::cpu_llvm_sync …
```
> Refactor pytest collection to anchor on test case files, not .mlir files.

- e2eshark/tools/aztestsetup.py
When try to download onnx model from public onnxstorage, the address is wrong. Here is the way to fixed it.
> Fix download address for onnx models

- iree_tests/download_remote_files.py
Progress on https://github.com/nod-ai/SHARK-TestSuite/issues/285
This is a simple improvement over serial processing, but it could still be improved further.
Looks like this shaves ~10 seconds off runs in this repo:
* Before 45s: https://github.com/nod-ai/SHARK-TestSuite/actions/runs/9996869262/job/27632145027#step:6:15
* After 35s: https://github.com/nod-ai/SHARK-TestSuite/actions/runs/9997455742/job/27634060037?pr=297#step:6:15
I saw 2m+ runs in IREE, hopefully this helps there too. Should be able to get the total time down to 10-20 seconds.
> Parallelize remote file downloads within each iree_tests directory.

- e2eshark/tools/aztestsetup.py
This reverts commit f6341055bfc4e2cd0db406db0903f6a28fa2fa8a.
https://github.com/nod-ai/SHARK-TestSuite/pull/290
Then the upload/download/run can provide list like this style: 
Upload a list of onnx model:
`python tools/aztestsetup.py -s /proj/ai_models/cnn/ipu_models/int8/vai_q_onnx// -m onnx/models/ResNet152_vaiq_int8/model.py -c huggingface_cache --setup --upload list_upload.txt`
**list_upload.txt** :
```
DarkNet53_vaiq
dla169_vaiq
```
Download a list of onnx model:
`
YOUR_AZ_KEY python tools/aztestsetup.py --cachedir  /proj/gdba/shark/cache --download listrun.txt 
`
**listrun.txt** :
```
onnx/models/DarkNet53_vaiq
onnx/models/dla169_vaiq
```
Run a list of onnx models: 
`python ./run.py  --tolerance 0.001 0.001 --cachedir /proj/gdba/shark/cache -f onnx -g models --mode onnx --report -j …
> Revert "Fix download address for onnx models (#290)"

- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/onnx_tests/models/deeplab.py
- alt_e2eshark/onnx_tests/models/model.py
- alt_e2eshark/run.py
Running this deeplab example will download an example image, load and transform it, run it through the test, then save the gold_output and output images. 
Unfortunately this is a private model example. I'll look and see if we have a public deeplab model to use as another example.
> [alt] Adds option for saving processed outputs and a deeplab example

- alt_e2eshark/e2e_testing/registry.py
- alt_e2eshark/onnx_tests/combinations/multi_conv.py
- alt_e2eshark/onnx_tests/operators/conv.py
- alt_e2eshark/onnx_tests/operators/model.py
Also fixes an issue with my last commit. I didn't notice the issue since re-running tests doesn't generate a new model.onnx unless you delete the old one or make a new rundirectory. It might be good to rework this so that operator/combination tests automatically regenerate the model each time.
> [alt] Add class decorator registration and more Conv examples

- alt_e2eshark/e2e_testing/backends.py
- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/e2e_testing/onnx_utils.py
- alt_e2eshark/onnx_tests/combinations/model.py
- alt_e2eshark/onnx_tests/combinations/multi_conv.py
- alt_e2eshark/onnx_tests/combinations/quant_relu.py
- alt_e2eshark/onnx_tests/combinations/quant_resize.py
- alt_e2eshark/onnx_tests/combinations/shape_cos.py
- alt_e2eshark/onnx_tests/helper_classes.py
- alt_e2eshark/onnx_tests/models/azure_models.py
- alt_e2eshark/onnx_tests/models/deeplab.py
- alt_e2eshark/onnx_tests/models/opt_models.py
- alt_e2eshark/onnx_tests/models/vision_models.py
- alt_e2eshark/onnx_tests/operators/add.py
- alt_e2eshark/onnx_tests/operators/concat.py
- alt_e2eshark/onnx_tests/operators/conv.py
- alt_e2eshark/onnx_tests/operators/dynamic_quantize_linear.py
- alt_e2eshark/onnx_tests/operators/pad.py
- alt_e2eshark/onnx_tests/operators/resize.py
1. Adds a new file: `alt_e2eshark/onnx_tests/helper_classes.py`
2. Adds a base class for user-generated onnx models called `MakeAModel`. All that needs to be overridden are the methods `construct_nodes` and `construct_i_o_value_info`. See the many examples/docstrings for more details.
3. Adds a base class for truncating an onnx graph (i.e., to return an earlier node output) called `TruncatedModel`.
4. Moves `AzureDownloadableModel` to `helper_classes.py`
5. Adds the ability to modify the `onnxruntime.SessionOptions()`, through the overridable method `update_sess_options`, on a test-by-test-basis to disable optimizations which might cause the gold output to lose accuracy. E.g., quantized resize/ Gemm in ort CPU provider seems to cause a loss in numerical accuracy. With models like resnet …
> [alt] Add some helper classes for making tests

- alt_e2eshark/e2e_testing/backends.py
- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/e2e_testing/onnx_utils.py
- alt_e2eshark/e2e_testing/storage.py
- alt_e2eshark/e2e_testing/test_configs/onnxconfig.py
- alt_e2eshark/onnx_tests/models/migraphx.py
- alt_e2eshark/run.py
Adds `--mode=cl-onnx-iree` flag option which mirrors `--mode=onnx-iree` (default), but runs most stages via command line scripts rather than python bindings. This seems to work better for a few reasons:
1. Easier command-line reproducers for failures. (The script which fails is printed in the corresponding log file)
2. Memory management per stage is more contained and doesn't need to rely on python's garbage collector.
> [alt] Add a CL-based mode

- alt_e2eshark/e2e_testing/backends.py
- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/e2e_testing/onnx_utils.py
- alt_e2eshark/e2e_testing/storage.py
- alt_e2eshark/e2e_testing/test_configs/onnxconfig.py
- alt_e2eshark/onnx_tests/models/migraphx.py
- alt_e2eshark/run.py
This PR includes quite a few changes:
1. include a status notification for current stage
2. remove optimizations from the ort session used to get model signature
3. sort the test_list before running tests
4. modify inputs for an migraphx model
5. fix an issue that occurs when loading scalar tensors from .bin files
6. add names to un-named nodes when truncating onnx models
7. return to printing the whole exception on a stage failure
8. don't reproduce detail log contents in top level error messages.
> [alt] Misc updates

- alt_e2eshark/run.py
For some reason, the stages "construct_inputs" and "native_inference" had been duplicated in some prior commits. This was likely due to rearranging the stage order and sloppy git merges.
> [alt] remove duplicated stages

- alt_e2eshark/e2e_testing/logging_utils.py
- alt_e2eshark/run.py
Levels are:
0 (default) cleans nothing
1 removes files larger or equal to 500M
2 removes all .vmfb and .mlir files
3 removes all but .log files
4 removes all files
Sample usage:
```
python run.py --cleanup=2 <other-args>
```
This would delete .mlir and .vmfb files after each test.
Other changes introduced: new file `e2e_testing/logging_utils.py` for storing misc functions used for `log_dir` management in `run.py` script.
> add --cleanup flag for cleaning up files after each test.

- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/e2e_testing/logging_utils.py
- alt_e2eshark/e2e_testing/test_configs/onnxconfig.py
- alt_e2eshark/run.py
- alt_e2eshark/utils/report.py
1. adds a stage "benchmark" which is not included by default
2. implements benchmarking for mode = cl-onnx-iree
3. adds benchmark time to generated reports
4. adds a run.py command line arg `--benchmark` for convenience. 
Sample usage:
```
python run.py -m cl-onnx-iree --benchmark -t migraphx -v --report
```
generates:
|Stage|Count|
|--|--|
| Total | 30 |
| PASS | 12 |
| Numerics | 4 |
| results-summary | 0 |
| postprocessing | 0 |
| benchmark | 0 |
| compiled_inference | 2 |
| native_inference | 2 |
| construct_inputs | 0 |
| compilation | 7 |
| preprocessing | 0 |
| import_model | 3 |
| setup | 0 |
Test was run with the following arguments:
Namespace(device='local-task', backend='llvm-cpu', iree_compile_args=None, mode='cl-onnx-iree', torchtolinalg=False, stages=None, skip_stages=None, …
> [alt] add a benchmark stage

- alt_e2eshark/e2e_testing/logging_utils.py
- alt_e2eshark/e2e_testing/onnx_utils.py
- alt_e2eshark/e2e_testing/test_configs/onnxconfig.py
1. add opset-version flag for command line onnx_importer path
2. avoid calling dim_param_dict.keys if None
3. avoid division by zero in case a model has no outputs.
> [alt] Misc Fixes

- alt_e2eshark/onnx_tests/operators/conv.py
This particular Conv op signature was found to be causing numerics failures in a few models. E.g.,  "maxvit_rmlp_base_rw_224.sw_in12k"
> [alt] adds a numerics failure reproducer

- alt_e2eshark/utils/report.py
Here is a sample from testing the migraphx models:
**TOTAL TESTS = 30**
|Stage|# Passing|% of Total|% of Attempted|
|--|--|--|--|
| Setup | 30 | 100.0% | 100.0% |
| IREE Compilation | 20 | 66.7% | 66.7% |
| Gold Inference | 18 | 60.0% | 90.0% |
| IREE Inference Invocation | 16 | 53.3% | 88.9% |
| Inference Comparison (PASS) | 12 | 40.0% | 75.0% |
**TOTAL TESTS = 30**
|Stage|# Failed at Stage|% of Total|
|--|--|--|
| Setup | 0 | 0.0% |
| IREE Compilation | 10 | 33.3% |
| Gold Inference | 2 | 6.7% |
| IREE Inference Invocation | 2 | 6.7% |
| Inference Comparison | 4 | 13.3% |
Test was run with the following arguments:
Namespace(device='local-task', backend='llvm-cpu', iree_compile_args=None, mode='cl-onnx-iree', torchtolinalg=False, stages=None, skip_stages=None, benchmark=False, …
> [alt] generate better report summaries

- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/e2e_testing/onnx_utils.py
- alt_e2eshark/onnx_tests/models/nlp.py
Note: this causes each nlp model to create an additional onnx inference session. A larger scale refactoring may be required to fix this.
Testing: I ran this on local with a bert model and was able to get to a numeric mismatch.
Full list of changes:
1. Refactor input generation for ONNX models:
- Split `get_node_shape_from_dim_param_dict()` out of 
`generate_input_from_node()` for better modularity.
- Improve docstrings for better function descriptions.
2. Enhance type annotations:
- Add return type hints to `construct_inputs()` and 
`get_sample_inputs_for_onnx_model()`.
- Use `TestTensors` type consistently for input/output tensors.
3. Fix NLP(Bert)-specific input generation:
- Override `construct_inputs()` in NLP models to handle 'token_type_ids'
correctly.
> Fix bert nlp models failing input generation by overriding `token_type_ids` to limit its range to [0,2) and some refactoring

- alt_e2eshark/e2e_testing/onnx_utils.py
In <https://github.com/nod-ai/SHARK-TestSuite/commit/776822a59c10a47c1778a5b4b8d257c34bba9ee5>, a line of code was erroneously removed, resulting in a failure to get the input shape for static dims. 
This adds back in the missing line to append the static shapes to the int_dims list.
> [alt] fix for issue with input generation

- alt_e2eshark/onnx_tests/models/azure_models.py
- alt_e2eshark/onnx_tests/models/nlp.py
- alt_e2eshark/run.py
Resolves issues <https://github.com/nod-ai/SHARK-ModelDev/issues/860> <https://github.com/nod-ai/SHARK-ModelDev/issues/859> and <https://github.com/nod-ai/SHARK-ModelDev/issues/863>
- 5 tests should newly pass with this change (the vit models listed under "no_opset_update")
- 1 test "resnetv2_50x1_bit.goog_in21k_ft_in1k_vaiq" should go from an import fail to a Numerics fail.
> fix some test setups causing import failures

- alt_e2eshark/e2e_testing/test_configs/onnxconfig.py
- alt_e2eshark/onnx_tests/models/azure_models.py
I would normally add all of the torch related stuff to the "onnx-to-torch-backend-pipeline" but there is a common issue with slice ops having an int that's too big only when saving/loading an mlir file at the torch level. See <https://github.com/llvm/torch-mlir/issues/3621>.
Also adds a few models to the basic opt list, since they would need a whole 'nother cycle of shape inference and scalarization to clean themselves up. Good to know that it is possible to clean these up at the torch level though!
> make some adjustments to the torch-onnx to linalg pass pipeline

- alt_e2eshark/utils/check_regressions.py
Example usage:
```shell
python utils/check_regressions.py \
--new="new_report.json" \
--old="old_report.json" \
--report-file="comparison.md" \
--perf_tol_regression=0.01 \
--perf_tol_progression=0.01
```
Or `-r=0.01 -p=0.01` for shortened tolerance flags. 
Here is a manufactured sample from the `shark-test-suite.txt` models (fake data):
regression tolerance: 1.0%
progression tolerance: 1.0%
|model name|exit_status|analysis|old_time_ms|new_time_ms|change_ms|percent_change|
|---|---|---|---|---|---|---|
|ConvNeXt_vaiq_int8|Numerics|progression|1730.5054|1647.7364|-82.7691|-4.78%|
|model name|old_status|new_status|
|---|---|---|
|KeypointRCNN_vaiq_int8|compilation|preprocessing|
|retinanet_resnet50_fpn_vaiq_int8|compilation|preprocessing|
|model name|old_status|new_status|
|---|---|---| …
> Add a tool to check for test regressions

- iree_tests/.gitattributes
I think this will help if the file contents change, preventing git from trying to merge files as text. I _hoped_ this would also show the files as binary, but that isn't working:
* Correctly binary: https://github.com/nod-ai/SHARK-TestSuite/blob/main/iree_tests/onnx/node/generated/test_abs/output_0.npy
* Incorrectly text: https://github.com/nod-ai/SHARK-TestSuite/blob/main/iree_tests/onnx/node/generated/test_abs/output_0.bin
We're already saving those files as binary, so something in the file extensions might be special cased ¯\\\_(ツ)\_/¯
> Treat .bin files as binary in git.

- alt_e2eshark/e2e_testing/storage.py
- alt_e2eshark/onnx_tests/helper_classes.py
Find the bug when debug https://github.com/nod-ai/SHARK-TestSuite/pull/371. Get this small fix merged first.
> Fix the bug for truncated model

- alt_e2eshark/e2e_testing/storage.py
The format character "l" corresponds to a 4-byte integer on some systems, but it can be 8 bytes on others, depending on the platform. To ensure consistency, use "i" for a 4-byte integer or "q" for an 8-byte integer explicitly.
```
python ./run.py --mode=cl-onnx-iree -v -t mygpt4_trunc_Reshape_0 --torchtolinalg
Stages to be run: ['setup', 'import_model', 'preprocessing', 'compilation', 'construct_inputs', 'native_inference', 'compiled_inference', 'postprocessing']
Test list: ['mygpt4_trunc_Reshape_0']
running test mygpt4_trunc_Reshape_0...
{'Shape': 1, 'Cast': 2, 'Slice': 1, 'Concat': 1, 'Reshape': 1}
PASSED                               
Test Summary:
PASSES: 1
TOTAL: 1
results stored in /proj/gdba/shark/chi/src/SHARK-TestSuite/alt_e2eshark/test-run
```
> Fix int32 unpack buffer size

- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/e2e_testing/logging_utils.py
- alt_e2eshark/run.py
- alt_e2eshark/utils/find_duplicate_models.py
When running `python run.py <other-args> --get-metadata`, this will save a dictionary with the model size and op frequencies to the log directory.
After a run, you can use `python utils/find_duplicate_models.py` to save or print a json dump of redundant models.
- "-s" "--simplified" will only return the list of model names (doesn't include the corresponding metadata).
- "-o" "--output" allows specifying the name of a json file you want to save the result to.
- "-r" "--rundirectory" allows specifying a different run directory to search, if `run.py` was run with a non-default run directory arg. 
I saved the tests below to a file called `sample.txt`.
```
add_test
model--bart-base-booksum--KamilAin
model--bart-base-cnn--ainize
model--bart-base-few-shot-k-1024-finetuned-squad-seed-2--anas-awada …
```
> Add ability to gather and analyse some model metadata

- alt_e2eshark/e2e_testing/storage.py
- alt_e2eshark/onnx_tests/helper_classes.py
- alt_e2eshark/onnx_tests/models/azure_models.py
- alt_e2eshark/onnx_tests/models/migraphx.py
- alt_e2eshark/onnx_tests/models/vision_models.py
- alt_e2eshark/onnx_tests/operators/generate_node.py
Uses dictionaries to associate torch dtypes to various strings used in storage utility functions. 
Also sets opset versions for node tests and cleans up the code there.
> cleans up `storage.py` and updates node tests

- alt_e2eshark/onnx_tests/models/migraphx.py
With a fix in <https://github.com/llvm/torch-mlir/pull/3844> for the model compilation issue, this test will pass with the change present here.
> fix bert__bert-large-uncased input gen

- .github/workflows/test_e2eshark.yml
- alt_e2eshark/e2e_testing/backends.py
- alt_e2eshark/run.py
This pulls in the required changes to run nightly CI for alt e2eshark.
Few things to iterate on here:
- Figure out a way to run a loop/matrix on a step so we don't have a bunch of download commands in push artifact step
- Figure out how to not fail the download artifact step if an artifact for a certain shard is not available
- Pull the merge report script calls, creating directories, copy pasting artifacts to eventually push into the reports repo into a python script that won't fail if certain shards fail and are not available
Just merging this in so we have a nightly going that doesn't depend on manual triggers. We can iterate on it. Has been running fine for the last week.
> Pulling in Alt E2ESHARK CI changes

- alt_e2eshark/onnx_tests/models/azure_models.py
1. Three `jx_nest_*` models will newly pass with basic optimizations. 
2. Three `twins_svt_*` models will now pass iree inference invocation, but fail numerics quite terribly. 
3. The `bat_resnext` model will still fail compile due to a similar error as in <https://github.com/iree-org/iree/issues/19058>
> add seven compile failure models to basic opt list

- alt_e2eshark/onnx_tests/models/azure_models.py
- alt_e2eshark/onnx_tests/models/nlp.py
We also need the importer change from <https://github.com/llvm/torch-mlir/pull/3875> for these to work. The primary issue is that updating the opset version requires the model to be smaller than 2GB. I've found a hacky way to update the opset version without loading external data, and this is the result.
**TOTAL TESTS = 49**
|Stage|# Passing|% of Total|% of Attempted|
|--|--|--|--|
| Setup | 49 | 100.0% | 100.0% |
| IREE Compilation | 41 | 83.7% | 83.7% |
| Gold Inference | 41 | 83.7% | 100.0% |
| IREE Inference Invocation | 41 | 83.7% | 100.0% |
| Inference Comparison (PASS) | 31 | 63.3% | 75.6% |
**TOTAL TESTS = 49**
|Stage|# Failed at Stage|% of Total|
|--|--|--|
| Setup | 0 | 0.0% |
| IREE Compilation | 8 | 16.3% |
| Gold Inference | 0 | 0.0% |
| IREE Inference Invocation | 0 | 0.0% | …
> Update opset version without weights for large nlp models

- alt_e2eshark/onnx_tests/models/onnx_zoo_models.py
Adds an empty custom_registry to `onnx_zoo_models.py` so that models from the ONNX Model Zoo can be added to various lists on a per-need basis depending on CI runs.
> Add empty custom_registry for ONNX Zoo Models

- alt_e2eshark/e2e_testing/storage.py
- alt_e2eshark/onnx_tests/helper_classes.py
To remove inconsistencies across different Python versions and have uniform behavior, replace all file paths constructed by string concatenation with a call to `os.path.join()`.
> Replace string concatenated paths by os.path.join()

- alt_e2eshark/e2e_testing/storage.py
Adds a guard to load from the input protobuf files only when inputs are requested in the case of ONNX Zoo models.
> Fix tensor loading for ONNX Zoo Models

- alt_e2eshark/base_requirements.txt
Adds the package `tf-keras` to `base_requirements.txt` for backwards compatibility in HuggingFace models that require `tensorflow` during export.
> Add `tf-keras` to required packages

- alt_e2eshark/base_requirements.txt
- alt_e2eshark/e2e_testing/backends.py
- alt_e2eshark/e2e_testing/framework.py
- alt_e2eshark/e2e_testing/storage.py
- alt_e2eshark/e2e_testing/test_configs/onnxconfig.py
- alt_e2eshark/iree_requirements.txt
- alt_e2eshark/onnx_tests/helper_classes.py
- alt_e2eshark/onnx_tests/models/flux.py
- alt_e2eshark/onnx_tests/models/model.py
- alt_e2eshark/run.py
The most significant infrastructure change is with some reworks to OnnxModelInfo:
1. `OnnxModelInfo` now has an attribute for `ExtraOptions`, which holds test-specific options for later testing stages beyond setup. This was required to allow running with external params, passing compile flags, and setting custom mlir import options.
2. All attributes configurable via `update_*` methods in `OnnxModelInfo` are updated in the init method immediately. This required reworking a few helper classes which relied on calling these at a specific time. 
Another infrastructure change is through the migration to using `iree-import-onnx` rather than torch-mlir's onnx importer. This is to allow externalizing parameters. 
Adds the following three tests:
- `flux_1_dev_transformer`
- `flux_1_dev_clip`
- …
> Add Flux_1.dev transformer and text encoder tests

- alt_e2eshark/onnx_tests/helper_classes.py
Adds overrides for `update_extra_options()` to `AzureDownloadableModel` and `OnnxModelZooDownloadableModel` to set opset version to 21 during import.
Fixes CI failures introduced by the removal of the `--opset-version` flag in commit `9215c13b696aa8ca767207c15e63a2dff6eccccf`.
> Default to opset 21 in extra_options for ONNX models

- alt_e2eshark/e2e_testing/storage.py
- alt_e2eshark/onnx_tests/helper_classes.py
- alt_e2eshark/onnx_tests/models/hf_models.py
- alt_e2eshark/run.py
This patch
1. fixes setup for zoo models to align with `update_*` methods getting called in `__init__`
2. updates opset version for hf models on import by default
3. moves an import of optimum into the HF model info class `__init__` method
4. applies black formatting
> Cleanup issues with a few helper classes

- alt_e2eshark/onnx_tests/helper_classes.py
Adds a check that disables `turnkey_stats.yaml` from begin downloaded for validated ONNX Zoo models. This resolves a YAML parsing error arising from corrupted downloads.
> Fix setup failure for validated ONNX Zoo Models

- alt_e2eshark/utils/find_duplicate_models.py
If running 
```
python run.py -t <some_test_1> -v -r test-run1 --get-metadata
```
and 
```
python run.py -t <some_test_2> -v -r test-run2 --get-metadata
```
Then 
```
python utils/find_duplicate_models.py -r . 
```
from the `alt_e2eshark` directory will identify duplicates from both `./test-run1/` and `./test-run2/`.
> Allows duplicate finder tool to search within multiple run directories

- alt_e2eshark/onnx_tests/models/hf_models.py
Fixes the bug introduced in commit:
"Fixes native inference input size mistmatch issue (#447)"
tokenizer.model_input_names should be updated before tokenizer call.
> Fixes the bug of moving input_names after tokenizer call

- alt_e2eshark/onnx_tests/models/hf_models.py
Following testcases passes after fixing input issue at construct_input phase (which was causing failure at compiled_inference phase):
```
hf_ko-sroberta-multitask
hf_robertuito-sentiment-analysis
hf_sbert_large_nlu_ru
hf_sentence-bert-base-ja-mean-tokens-v2
```
> Fixes compiled_inference by fixing input size issue

- alt_e2eshark/onnx_tests/operators/loop.py
This adds a basic e2e test for `onnx.Loop`. Requires the fixes from llvm/torch-mlir#4064 and llvm/torch-mlir#4098 in order to pass.
> Add basic `onnx.Loop` test

- alt_e2eshark/onnx_tests/operators/loop.py
This adds a basic e2e test for `onnx.Loop`. Requires the fixes from llvm/torch-mlir#4064 and llvm/torch-mlir#4098 in order to pass.
> Add basic `onnx.Loop` test (#461)
